export const textCollection: string[][] = [
  ["Janis", "ist", "hot AF"],
  ["Janis", "ist ein", "Petanque", "König"],
  ["Janis", "ist ein", "Kite-Hero"],
  ["Janis", "schafft", "alles was", "er will"],
  ["Janis", "wird von", "uns geliebt"],
  ["Janis", "ist eine", "Partymaus"],
  ["Janis", "hört", "gut zu"],
  ["Janis", "ist für", "uns da"],
  ["Janis", "ist ein", "guter", "Hugger"],
  ["Janis", "hat", "guten", "Humor"],
  ["Janis", "haben wir", "immer gerne", "bei uns"],
  ["Janis", "bringt", "uns zum", "lachen"],
  ["Janis", "hat eine", "sexy Frisur"],
  ["Janis", "sorgt", "für gute", "Laune"],
  ["Janis", "ist ein", "Abenteurer"],
  ["Janis", "ist gute", "Gesell-", "schaft"],
  ["Janis", "bereichtet", "jede", "Diskussion"],
  ["Janis", "ist ein", "guter", "Freund"],
  ["Janis", "versteht", "einem"],
  ["Janis", "ist ein", "heiterer", "Mensch"],
  ["Janis", "haben wir", "fest gerne"],
  ["Janis", "ist ein", "super DJ"],
  ["Janis", "freut sich", "mit einem"],
  ["Janis", "ist ein", "Sonnenschein"],
];

export const colors: string[] = [
  "#f4d03f",
  "#f9b56b",
  "#fdc496",
  "#ffdba9",
  "#ffedbf",
  "#ffeecd",
  "#f9f9ee",
  "#ededde",
  "#c7defd",
  "#bcecfb",
  "#e64e72",
  "#4596c2",
  "#f6d55c",
  "#d65b4a",
  "#f9ad61",
  "#ca85e0",
  "#87d5ab",
  "#2ebd85",
  "#f2d9de",
  "#f6b6bc",
  "#ff9a8b",
  "#8a84e2",
  "#72c0d3",
  "#e597d4",
  "#6a4c93",
  "#d6336c",
  "#009688",
  "#f39c12",
  "#c0392b",
  "#3498db",
  "#27ae60",
  "#e74c3c",
  "#2980b9",
  "#c0392b",
  "#1abc9c",
  "#f1c40f",
];
