export const textCollection: string[][] = [
  ["Janis", "ist ein", "Petanque", "König"],
  ["Janis", "ist ein", "Kite-Hero"],
  ["Janis", "ist", "hot AF"],
  ["Janis", "schafft", "alles was", "er will"],
  ["Janis", "wird von", "uns geliebt"],
  ["Janis", "ist eine", "Partymaus"],
  ["Janis", "hört", "gut zu"],
  ["Janis", "ist für", "uns da"],
  ["Janis", "ist ein", "guter", "Hugger"],
  ["Janis", "hat", "viel Humor"],
  ["Janis", "haben wir", "immer gerne", "bei uns"],
  ["Janis", "bringt", "uns zum", "lachen"],
  ["Janis", "hat eine", "sexy Frisur"],
  ["Janis", "sorgt", "für gute", "Laune"],
  ["Janis", "ist ein", "Abenteurer"],
  ["Janis", "ist gute", "Gesellschaft"],
  ["Janis", "bereichtet", "jede", "Diskussion"],
  ["Janis", "ist ein", "guter Freund"],
  ["Janis", "versteht", "einen"],
  ["Janis", "ist ein", "aufgestellter", "Mensch"],
  ["Janis", "haben wir", "fest gerne"],
  ["Janis", "ist ein", "super DJ"],
];

export const colors: string[] = [
  "#f4d03f",
  "#f9b56b",
  "#fdc496",
  "#ffdba9",
  "#ffedbf",
  "#ffeecd",
  "#f9f9ee",
  "#ededde",
  "#c7defd",
  "#bcecfb",
  "#e64e72",
  "#4596c2",
  "#f6d55c",
  "#d65b4a",
  "#f9ad61",
  "#ca85e0",
  "#87d5ab",
  "#57458c",
  "#2ebd85",
  "#f2d9de",
  "#f6b6bc",
  "#ff9a8b",
  "#8a84e2",
  "#72c0d3",
  "#e597d4",
];
